platform :ios, ‘9.0’
use_frameworks!

pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

pod 'Alamofire', '~> 2.0'

pod 'Parse'

pod 'ParseUI'

